version: "2"

services:
  voting-app:
    build: ./voting-app/.
    volumes:
     - ./voting-app:/app
    ports:
      - "5000:9080"
    links:
      - redis
    networks:
      - front-tier
      - back-tier

  result-app:
    build: ./result-app/.
    volumes:
      - ./result-app:/app
    ports:
      - "5001:9080"
    links:
      - db
    networks:
      - front-tier
      - back-tier

  worker:
    build: ./worker
    links:
      - db
      - redis
    networks:
      - back-tier

  redis:
    image: redis
    ports: ["6379"]
    networks:
      - back-tier

  db:
    build: ./db2/.
    ports: 
       - "50000:50000"
    environment:
      DB2INST1_PASSWORD: db2inst1
      LICENSE: accept
    command: db2start
    volumes:
      - "db-data:/home/db2inst1/db2inst1"
    networks:
      - back-tier

volumes:
  db-data:

networks:
  front-tier:
  back-tier:


